apiVersion: v1
kind: Namespace
metadata:
  name: demo-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-plugin
  namespace: demo-plugin
  labels:
    app: demo-plugin
    app.kubernetes.io/component: demo-plugin
    app.kubernetes.io/instance: demo-plugin
    app.kubernetes.io/part-of: demo-plugin
    app.openshift.io/runtime-namespace: demo-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-plugin
  template:
    metadata:
      labels:
        app: demo-plugin
    spec:
      containers:
        - name: demo-plugin
          image: quay.io/gshanmug/demo-plugin:latest
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          args:
            - "--ssl"
            - "--cert=/var/serving-cert/tls.crt"
            - "--key=/var/serving-cert/tls.key"
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: demo-plugin
  namespace: demo-plugin
  labels:
    app: demo-plugin
    app.kubernetes.io/component: demo-plugin
    app.kubernetes.io/instance: demo-plugin
    app.kubernetes.io/part-of: demo-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: demo-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: demo-plugin
  annotations:
    console.openshift.io/use-i18n: "true"
spec:
  displayName: "OpenShift Console Demo Plugin"
  service:
    name: demo-plugin
    namespace: demo-plugin
    port: 9001
    basePath: "/"
